### ISSUE TITLE
Missing Tolerations in helm chart

### ISSUE THREAD

**Issue by anwaramoon** [Azure/gitops-connector#23]
Hi, 

We are trying out this connector with Flux2. But we are having issues with helm chart as our nodes are tainted. 

Tolerations are missing in helm chart. Can you please add them. I can also submit a PR if thats ok.

Thanks

**Comment by eedorenko** [comment]
Hi @anwaramoon. Sorry for the late response. Vacation time:) 
Your PR will be very welcome on this.

**Comment by anwaramoon** [comment]
Hi @eedorenko No probs. I have created PR. Please review. Thanks

**Comment by anwaramoon** [comment]
Thanks @eedorenko
