### ISSUE TITLE
gitops-connector + Azur Arc

### ISSUE THREAD

**Issue by ferdy-design** [Azure/gitops-connector#26]
Hey,

Is it possible to use gitops-connector with Azure Arc? 

I have managed to install the gitops-connector on my cluster, but I don't know what to configure FluxCD with to send notifications to GitOps connector. From the documentation GitRepository or Kustomization are used as eventSources, I don't have any of those resources in my cluster because Flux is installed using Azure Arc, and it doesn't seem to create those resources/controllers in the cluster. 

Do I have to use native Flux for this to work?

**Comment by dtzar** [comment]
@ferdy-design sorry for the delay in response!  Are you now using the new Flux v2 implementation of Azure Arc?  If so, it should work - else it definitely won't with the v1 version of flux.
@jonathan-innis FYI

**Comment by eedorenko** [comment]
@ferdy-design you can follow [this tutorial](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-gitops-flux2-ci-cd) for the Azure Arc setup with Flux V2.
