### ISSUE TITLE
Pls make a new release for NewArtifact issue

### ISSUE THREAD

**Issue by ezunwng** [Azure/gitops-connector#36]
Hi: 

We encountered the following issue. And I checked the submit of gitops-connector. Looks this issue is fixed last month.
In our test, once this issue happened, gitops-connector will execute "attempting task completion callback" incorrectly.
So could you make a new release with this bug fix asap?

INFO:root:Finished PR cleanup, sleeping for 30 seconds...
DEBUG:root:GitOps phase: {'involvedObject': {'kind': 'GitRepository', 'namespace': 'flux-system', 'name': 'flux-system', 'uid': '448b6503-1326-4f84-b5eb-65d636cf4092', 'apiVersion': 'source.toolkit.fluxcd.io/v1beta2', 'resourceVersion': '3265499'}, 'severity': 'info', 'timestamp': '2022-10-11T14:15:23Z', 'message': "stored artifact for commit 'Merged PR 60360: [task] deploy ccrc'", 'reason': 'NewArtifact', 'metadata': {'revision': 'main/5497a27ed48fa3fb414e5cb714f8d01ca84aed6c'}, 'reportingController': 'source-controller', 'reportingInstance': 'source-controller-958559676-tp8cw'}
DEBUG:root:Kind: GitRepository
ERROR:gitops_event_handler:Exception on /gitopsphase [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/gitops_event_handler.py", line 33, in gitopsphase
    gitops_connector.process_gitops_phase(payload, req_time)
  File "/app/gitops_connector.py", line 29, in process_gitops_phase
    self._queue_commit_statuses(phase_data, req_time)
  File "/app/gitops_connector.py", line 35, in _queue_commit_statuses
    commit_statuses = self._gitops_operator.extract_commit_statuses(phase_data)
  File "/app/operators/flux_gitops_operator.py", line 22, in extract_commit_statuses
    reason_message = self._map_reason_to_description(
  File "/app/operators/flux_gitops_operator.py", line 150, in _map_reason_to_description
    return reason_description_map[reason]
KeyError: 'NewArtifact'
DEBUG:root:GitOps phase: {'involvedObject': {'kind': 'Kustomization', 'namespace': 'flux-system', 'name': 'infrastructure', 'uid': 'ad7b55b3-4cee-484f-986c-4919cfe85b80', 'apiVersion': 'kustomize.toolkit.fluxcd.io/v1beta2', 'resourceVersion': '3265521'}, 'severity': 'info', 'timestamp': '2022-10-11T14:15:23Z', 'message': 'Reconciliation finished in 330.665831ms, next run in 30m0s', 'reason': 'ReconciliationSucceeded', 'metadata': {'commit_status': 'update', 'revision': 'main/5497a27ed48fa3fb414e5cb714f8d01ca84aed6c'}, 'reportingController': 'kustomize-controller', 'reportingInstance': 'kustomize-controller-5b96477d7f-f46x6'}
DEBUG:root:Kind: Kustomization
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dev.azure.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dev.azure.com:443
DEBUG:urllib3.connectionpool:https://dev.azure.com:443 "POST /ericsson/Flux_Poc/_apis/git/repositories/Flux_Poc/commits/5497a27ed48fa3fb414e5cb714f8d01ca84aed6c/statuses?api-version=6.0 HTTP/1.1" 201 887
DEBUG:urllib3.connectionpool:https://dev.azure.com:443 "GET /ericsson/Flux_Poc/_apis/git/repositories/Flux_Poc/commits/5497a27ed48fa3fb414e5cb714f8d01ca84aed6c?api-version=6.0 HTTP/1.1" 200 985
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dev.azure.com:443
DEBUG:urllib3.connectionpool:https://dev.azure.com:443 "GET /ericsson/Flux_Poc/_apis/git/repositories/Flux_Poc/pullRequests/60360/properties?api-version=6.0-preview HTTP/1.1" 200 512
INFO:root:PR 60360: Rollout True, attempting task completion callback...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ericsson.visualstudio.com:443
DEBUG:urllib3.connectionpool:https://ericsson.visualstudio.com:443 "GET /d734cc11-29df-47c5-a5ee-3d2f5108ff58/_apis/distributedtask/hubs/build/plans/066b0f13-863f-4c1d-9e9b-201abadcb0aa HTTP/1.1" 200 665
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ericsson.visualstudio.com:443
DEBUG:urllib3.connectionpool:https://ericsson.visualstudio.com:443 "POST /d734cc11-29df-47c5-a5ee-3d2f5108ff58/_apis/distributedtask/hubs/build/plans/066b0f13-863f-4c1d-9e9b-201abadcb0aa/events?api-version=2.0-preview.1 HTTP/1.1" 204 0
DEBUG:root:Update PR task response contentb''
INFO:root:PR 60360: Successfully completed task c0e4c74c-be1d-5fa9-b73b-72a8d2302878

Best regards
Zhiyun Wang

**Comment by eedorenko** [comment]
Fixed in 1.2.0 release
