### ISSUE TITLE
Gitops-connector only support 1 kustomization per gitops repo

### ISSUE THREAD

**Issue by scottunik** [Azure/gitops-connector#40]
Does the gitops-connector only support 1 kustomization per gitops repo.

Our workflow has multiple Kustomization  per gitops repo.  When running multiple kustomization the dev kustomization event triggers the staging kustomization  and vice versa.

**Comment by eedorenko** [comment]
No. It doesn't support multiple git repositories, but number of kustomizations per gitops repo doesn't matter. Could you please provide more details on your use case?
