### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by ageisen2000** [Azure/gitops-connector#50]
Specifically this line:

```Refer to [a sample of such agentless task](https://github.com/Azure/arc-cicd-demo-src/blob/FluxV2/.pipelines/pr-completion-task-template.yaml) for the implementation details.```

I'm not sure where this should link or i'd put in a PR

**Comment by vmartinlantek** [comment]
The correct link seems to be this one: https://github.com/Azure/arc-cicd-demo-src/blob/master/.pipelines/pr-completion-task-template.yaml

**Comment by eedorenko** [comment]
Fixed by #46
