### ISSUE TITLE
When autocomplete is used, the PR number cannot be retrieved

### ISSUE THREAD

**Issue by vmartinlantek** [Azure/gitops-connector#54]
When autocomplete is used, the PR merged message changes (no longer starts with Merged PR) and it is not possible to retrieve the PR number

```
def get_pr_num(self, commit_id) -> str:
        comment = self.get_commit_message(commit_id)
        MERGED_PR = "Merged PR "
```

The actual message is 

```
"comment": "Merge pull request XXXX from dev/YYYY/zzzzz into main",
```

**Comment by pareion** [comment]
I had the same issue as you; luckily for me, I set the autocomplete through the Azure CLI command to update the pull request.

There is a parameter you can supply called `--merge-commit-message`, which you can add `Merged PR ` to.

`az repos pr update --id ${{ parameters.pullRequestId }} --auto-complete --org "${{ parameters.organization }}" --merge-commit-message "Merged PR ${{ parameters.pullRequestId }}: $title"`.

However, I haven't found a way of handling it through the UI in Azure DevOps..
