### ISSUE TITLE
Support workload identity

### ISSUE THREAD

**Issue by rouke-broersma** [Azure/gitops-connector#59]
Since azure devops now supports managed identity it would be nice to be able to use aks workload identity instead of PAT for authentication with azure devops.

**Comment by Jaykul** [comment]
Is this project still active? I'm getting a lot of pressure to ditch systems that require regular human intervention (in the form of generating PAT tokens by hand), and since we can't generate PAT tokens for managed identities, we really need this.

**Comment by eedorenko** [comment]
PRs are welcome!
